// <auto-generated />
using EmployeeManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(AppDbContex))]
    [Migration("20211202204721_DumyData")]
    partial class DumyData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 1,
                            Email = "caslav@osvezenje.com",
                            Name = "Caslav"
                        },
                        new
                        {
                            Id = 2,
                            Department = 2,
                            Email = "vanjuka@osvezenje.com",
                            Name = "Vanja"
                        },
                        new
                        {
                            Id = 3,
                            Department = 3,
                            Email = "fedjika@osvezenje.com",
                            Name = "Fedja"
                        },
                        new
                        {
                            Id = 4,
                            Department = 4,
                            Email = "oko@osvezenje.com",
                            Name = "Oksana"
                        },
                        new
                        {
                            Id = 5,
                            Department = 5,
                            Email = "cobra@osvezenje.com",
                            Name = "Kobrim"
                        },
                        new
                        {
                            Id = 6,
                            Department = 6,
                            Email = "jk@osvezenje.com",
                            Name = "Jekara"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
